name: Analysis Workflow

on:
  pull_request:
  push:
  workflow_dispatch: # Manual trigger

jobs:
  static_analysis:
    name: Static Analysis with semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      - name: Run semgrep
        run: semgrep

  dockerfile_analysis:
    name: Dockerfile Analysis with hadolint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run hadolint
        run: docker run --rm -i hadolint/hadolint < Dockerfile
